config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :referrals
  mount Ckeditor::Engine => '/ckeditor'
  get 'pages/about'

  
  
  get 'pages/career'
  get 'pages/robots'
  
  get 'jobs/findjobs'
  
  

  get 'about', :to => 'pages#about'
  
  get 'career', to: 'pages#career'
  get 'robots', to: 'pages#robots.txt'

  get 'findjobs', to: 'jobs#findjobs'
  
  
  
  resources :japprovals
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :jobs
  resources :locations
  resources :genders
  resources :jtypes
  resources :modes
  resources :categories
  resources :pages
  resources :uploads
  resources :contacts
  get 'home/index'

 
  root 'jobs#index'
  
  
  
  ActiveAdmin.routes(self)
  get '*path', to: 'jobs#index'
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
		attr_accessible :company, :contactperson, :contactemail, :contactno, :description
		
		validates :contactperson, presence:true, length: {minimum:3, maximum:30}
		VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i	#         /^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/+\z/i
		validates :contactemail, presence:true, format: { with: VALID_EMAIL_REGEX }, length: {minimum:6, maximum:30}
		validates :contactno, numericality: true, length: {minimum:10, maximum:13}   # Need to create logic ,only number and + sign
		validates :description, presence:true, length: {minimum:10, maximum:3000}
	
end

app/models/gender.rb
class Gender < ActiveRecord::Base
end

app/models/japproval.rb
class Japproval < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
	attr_accessible :title, :company, :comurl, :designation, :minsalary, :maxsalary, :minexp, :maxexp, :category_id, :location_id, :mode_id, :jtype_id, :nperiod, :gender_id, :contactperson, :contactemail, :contactno, :description, :japproval_id
	belongs_to :category
	belongs_to :location
	belongs_to :mode
	belongs_to :jtype
	belongs_to :gender
	belongs_to :japproval
	
	
	validates :title, presence:true, length: {minimum:2, maximum:50}
	validates :company, presence:true, length: {minimum:3, maximum:50}
	validates :comurl, presence:true, length: {minimum:4, maximum:50}
	validates :minexp, presence:true, numericality: true, length: {minimum:1, maximum:2}
	validates :maxexp, presence:true, numericality: true, length: {minimum:1, maximum:2}
	validates :nperiod, presence:true, numericality: true, length: {minimum:1, maximum:2}
	validates :contactperson, presence:true, length: {minimum:3, maximum:50}
	
	validates :category, presence:true
	validates :location, presence:true
	validates :mode, presence:true
	validates :jtype, presence:true
	VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i	#         /^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/+\z/i
	validates :contactemail, presence:true, format: { with: VALID_EMAIL_REGEX }, length: {minimum:6, maximum:30}
	validates :contactno, presence:true, numericality: true, length: {minimum:10, maximum:13}   # Need to create logic ,only number and + sign
	validates :description, presence:true, length: {minimum:10, maximum:5000}
	
end

app/models/jtype.rb
class Jtype < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/mode.rb
class Mode < ActiveRecord::Base
end

app/models/referral.rb
class Referral < ActiveRecord::Base
    attr_accessible :fname, :lname, :company, :comurl, :designation, :currsalary, :expsalary, :exp, :location_id, :mode_id, :jtype_id, :nperiod, :gender_id, :contactemail, :contactno, :resume, :attachment, :jobid, :attachment_cache
    belongs_to :location
    belongs_to :mode
    belongs_to :jtype
    belongs_to :gender

	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
	
    validates :fname, presence:true, length: {minimum:2, maximum:15}
    validates :lname, presence:true, length: {minimum:2, maximum:15}
    validates :company, presence:true, length: {minimum:2, maximum:15}
    validates :comurl, presence:true, length: {minimum:4, maximum:30}
    validates :designation, presence:true, length: {minimum:2, maximum:30}
	validates :nperiod, presence:true, numericality: true, length: {minimum:1, maximum:2}
	
	validates :currsalary, presence:true, numericality: true, length: {minimum:1, maximum:2}
	validates :expsalary, presence:true, numericality: true, length: {minimum:1, maximum:2}
	validates :exp, presence:true, numericality: true, length: {minimum:1, maximum:2}
	validates :location, presence:true
	validates :mode, presence:true
	validates :jtype, presence:true
	
	VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i	#         /^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/+\z/i
	validates :contactemail, presence:true, format: { with: VALID_EMAIL_REGEX }, length: {minimum:6, maximum:40}
	validates :contactno, presence:true, numericality: true, length: {minimum:10, maximum:13}   # Need to create logic ,only number and + sign
	
	validates :attachment, presence:true
	
	validate :attachment_size_validation
	
	def attachment_size_validation
    errors[:attachment] << "should be less than 1MB" if attachment.size > 1.megabytes
    end
	
	    
end

app/models/upload.rb
class Upload < ActiveRecord::Base

 attr_accessible :attachment_cache
 
end

app/controllers/jobs_controller.rb
class JobsController < InheritedResources::Base
	rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
	rescue_from ActionView::MissingTemplate, :with => :record_not_found

   def index
		@jobs = Job.all.order('created_at DESC')
	end
	
	def new 
		@job = Job.new
		@category = Category.all	
		@japproval = Japproval.new
			
	end
	
	def create
		@job = Job.new(params[:job])
		@job.japproval_id ||= "1"	# To set the default value of japproval_id as pending
		@job.gender_id="4" if @job.gender_id.blank?
		if @job.save
			redirect_to new_job_path, :notice => "Your Job has been posted successfully,Please wait for Admin Approval"
		else
		    render "new"
		end
	end
	
		
	def show
		@job = Job.find(params[:id])
	end
	
	def findjobs
		@jobs = Job.all.order('created_at DESC')
	end
	
	
	
    private

    def record_not_found
		redirect_to root_path
    end

    def job_params
      params.require(:job).permit(:title, :company, :comurl, :designation, :minsalary, :maxsalary, :minexp, :maxexp, :category_id, :location_id, :mode_id, :jtype_id, :nperiod, :gender_id, :contactperson, :contactemail, :contactno, :description, :japproval_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/japprovals_helper.rb
module JapprovalsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/jtypes_helper.rb
module JtypesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/modes_helper.rb
module ModesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/referrals_helper.rb
module ReferralsHelper
end

app/views/jobs/findjobs.html.erb
<div class="main-page-title"><!-- start main page title -->
			<div class="container">
				<div class="post-job-title">Find Jobs</div>				
			</div>

</div><!-- end main page title -->
					


<div class="container">
		<div class="spacer-1">&nbsp;</div>
		<div class="row">
			<div class="col-md-8">
				<form role="form" class="post-job-form">
						<div class="row">
							<div class="form-group col-md-6">
								<strong>Enter search criteria</strong>								
								<input type="text" class="form-control" name="keyword" id="keyword" placeholder="Search By Skills, Title, Keywords">
							</div>	
							
						<!--	<div class="form-group col-md-6">	
								<strong>Location </strong>
								<input type="text" class="form-control" name="location" id="location" placeholder="Search By Bengaluru, Delhi, Pune, Mumbai">                                
							</div>	-->		
						</div>		
				
						<div class="submit-btn" style="margin-top: 25px;">
							<input type="submit" class="btn btn-green" name="submit" value="Search Jobs">
						</div> <br>
										
				</form>
				
				<% @keyword_key = params['keyword'] %>
				<% @count1 = 0 %> 
				<% @jobs.each do |job| %>
							<% if job.japproval.name == "Approved" %>															
								<% if ((job.description =~ (/#{@keyword_key}/i)) or (job.title =~ (/#{@keyword_key}/i)) or (job.location.name =~ (/#{@keyword_key}/i)) or (job.category.name =~ (/#{@keyword_key}/i)) or (job.company =~ (/#{@keyword_key}/i)) or (job.designation =~ (/#{@keyword_key}/i)) ) %>
			   
									<% @count1 = @count1+1 %>
								<% end %>
							<% end %>
				<% end %>	
				
				<% if @keyword_key.include? "Null" %>
					<br>
					<h4>Enter search criteria to filter jobs.</h4>
				<% elsif %>
							<% if @count1 != 0 %>
								<% if @keyword_key.empty? or @keyword_key.nil? %>	
									<h4> Displaying all recent jobs as search criteria is empty. Enter search criteria to filter jobs. </h4>
									<br>
								<% elsif %>								
									<h4>Job results that match your search criteria - <script type="text/javascript">
										document.write(qs("keyword"));
										</script></h4>
										<br>											
								<% end %>							
								<table width="100%" class="pure pure-table  pure-table-bordered pure-table-hover" id="results">
									<thead>
										<tr>
											<th width="42%">JOB DESCRIPTION</th>
											<th width="18%">COMPANY NAME</th>
											<th width="13%">LOCATION</th>
											<th width="13%">EXPERIENCE</th>                                                
											<th width="18%">POSTED</th>
											<th width="18%">Ask4Refferal</th>
									</tr>
									</thead>
									<tbody>
										<% @jobs.each do |job| %>							
											<% if job.japproval.name == "Approved" %>																				
												<% if ((job.description =~ (/#{@keyword_key}/i)) or (job.title =~ (/#{@keyword_key}/i)) or (job.location.name =~ (/#{@keyword_key}/i)) or (job.category.name =~ (/#{@keyword_key}/i)) or (job.company =~ (/#{@keyword_key}/i)) or (job.designation =~ (/#{@keyword_key}/i)) ) %>
													<% @localminexp = job.minexp %>
													<% @localmaxexp = job.maxexp %>
													<tr>
														<td><%= link_to job.title, job %></td>
														<td><%= job.company %></td>			  
														<td><%= job.location.name %></td>
														<td><%= "#{@localminexp} - #{@localmaxexp} Y" %></td>														
														<td><%= job.created_at.strftime("%d-%b-%Y") %></td>
														<td><%= link_to "Ask4Refferal", new_referral_path(:jobdesignation => job.designation) %></td>
													</tr>
												<% end %>
											<% end %>
										<% end %>						
									</tbody>
								</table>  
								
							<% elsif %>
								<br>
								<h4>There are no results that match your search criteria- <script type="text/javascript">
								document.write(qs("keyword"));
								</script></h4>
								<h5> Please try adjusting your search keywords. </h5>
							<% end %>
				<% end %>
				<h6 class="general_heading" style="cursor: pointer; cursor: hand; "><div id="pageNavPosition"></div></h6>	
			<br>
			</div>                                                    
    	


				
				
				
				<div class="col-md-3">
					<div class="job-side-wrap">
						<li><%= link_to "HOME", root_path %></li>
					</div>
					
					<div class="job-side-wrap">
						<li><%= link_to "POST JOBS", new_job_path %></li>
					</div>

					<div class="job-side-wrap">
						<li><%= link_to "FIND JOBS", findjobs_path(:keyword => "Null", :location => "Null")   %></li>
					</div>

					<div class="job-side-wrap">
						<li><%= link_to "ABOUT US", about_path %></li>
					</div>
					<div class="job-side-wrap">
						<li><%= link_to "CONTACT US", new_contact_path %></li>
					</div>
					<div class="job-side-wrap">
						<li><%= link_to "CAREERS", career_path %></li>	
					</div>
				</div>
			</div>
		</div>
		
		
		

		<div id="page-content"><!-- start content -->
			<div class="content-about">
				<div id="cs"><!-- CS -->
					<div class="container">
					<div class="spacer-1">&nbsp;</div>
						<h2>Facing problem in searching jobs? </h2>
						<p>
							Please send resume on admin@ask4referral.com
						</p>
						<h1 class="phone-cs">Call: +91-9945508524</h1>
					</div>
				</div><!-- CS -->
			</div><!-- end content -->
		</div><!-- end page content -->
		

app/views/jobs/new.html.erb
<div class="main-page-title"><!-- start main page title -->
			<div class="container">
				<div class="post-job-title">Post a Job</div>				
			</div>

</div><!-- end main page title -->
					
 
		
		
		<div class="container">
		<div class="spacer-1">&nbsp;</div>
			<% flash.each do |key,value| %>
				<p><%= value %></P>
			<% end %>
			<div class="row">
				<div class="col-md-8">
				
						<%= form_for(@job) do |f| %>
							<% if @job.errors.any? %>
							<div id="error_explanation">
								<b>Please fill mandatory field and try again</b>
							
								<li>
								<%= @job.errors.full_messages.first if @job.errors.any? %>
								</li>
							</div>
						<% end %><br>
						<form role="form" class="post-job-form">
						
						<div class="row">
						<div class="form-group col-md-6">
							<strong>Job Title *</strong>
							<%= f.text_field :title, placeholder: "Ex. Software Engineer, Quality Analyst", class: "form-control input" %>
						</div>

					   <div class="form-group col-md-6">
								<strong>Designation *</strong>
								<%= f.text_field :designation, placeholder: "Ex. R&D Engineer, Senior Developer", class: "form-control input" %>
						</div>
						</div>
						
						<div class="row">
						<div class="form-group col-md-6">							
							<strong>Job Location *</strong>
							<%= f.select :location_id, Location.all.collect {|x| [x.name ,x.id]}, {:include_blank => "Select One"}, class: "form-control" %>
						</div>
												
						<div class="form-group col-md-6">
								<strong>Preferred Notice Period *</strong>
								<%= f.select(:nperiod, [["Notice Period (Days)", ""],"0","1", "2", "3", "4", "5","6", "7", "8", "9", "10","11", "12", "13", "14", "15","16", "17", "18", "19", "20","21", "22", "23", "24", "25","26", "27", "28", "29", "30","31", "32", "33", "34", "35","36", "37", "38", "39", "40","41", "42", "43", "44", "45","46", "47", "48", "49", "50","51", "52", "53", "54", "55","56", "57", "58", "59", "60", "61", "62", "63", "64", "65","66", "67", "68", "69", "70", "71", "72", "73", "74", "75","76", "77", "78", "79", "80", "81", "82", "83", "84", "85","86", "87", "88", "89", "90"], {}, class: "form-control" ) %> 									
						</div>
						</div>
						
						<div class="row">
							<div class="form-group col-md-6">	
								<strong>Experience *</strong> 
								<div class="row">
									<div class="form-group col-md-6">
										<%= f.select(:minexp, [["Min Exp (Years)", ""],"0","1", "2", "3", "4", "5","6", "7", "8", "9", "10","11", "12", "13", "14", "15","16", "17", "18", "19", "20","21", "22", "23", "24", "25","26", "27", "28", "29", "30"], {}, class: "form-control") %>
									</div>	
									<div class="form-group col-md-6">
										<%= f.select(:maxexp, [["Max Exp (Years)", ""],"0","1", "2", "3", "4", "5","6", "7", "8", "9", "10","11", "12", "13", "14", "15","16", "17", "18", "19", "20","21", "22", "23", "24", "25","26", "27", "28", "29", "30"], {}, class: "form-control") %> 
									</div>	
								</div>								
							</div>
													
							<div class="form-group col-md-6">
									<strong>Job Category *</strong>
								<%= f.select :category_id, Category.all.collect {|x| [x.name ,x.id]}, {:include_blank => "Select One"}, class: "form-control"  %>
							</div>
						</div>
						
						<div class="row">
							<div class="form-group col-md-6">
								<strong>Job Type *</strong>
								<%= f.select :jtype_id, Jtype.all.collect {|x| [x.name ,x.id]}, {:include_blank => "Select One"}, class: "form-control" %>
							</div>

							<div class="form-group col-md-6">
								<strong>Job Mode *</strong>
								<%= f.select :mode_id, Mode.all.collect {|x| [x.name ,x.id]}, {:include_blank => "Select One"}, class: "form-control" %>
							</div>
						</div>
						
						<div class="row">
							<div class="form-group col-md-6">
								
							</div>

							<div class="form-group col-md-6">
								
							</div>
						</div>
						
						<div class="row">
							<div class="form-group col-md-6">	
								<strong>Salary Range (Optional)</strong> 
								<div class="row">
									<div class="form-group col-md-6">
										<%= f.select(:minsalary, [["Min Salary (LPA)", ""],"0","1", "2", "3", "4", "5","6", "7", "8", "9", "10","11", "12", "13", "14", "15","16", "17", "18", "19", "20","21", "22", "23", "24", "25","26", "27", "28", "29", "30"], {}, class: "form-control") %>
									</div>	
									<div class="form-group col-md-6">
										<%= f.select(:maxsalary, [["Max Salary (LPA)", ""],"0","1", "2", "3", "4", "5","6", "7", "8", "9", "10","11", "12", "13", "14", "15","16", "17", "18", "19", "20","21", "22", "23", "24", "25","26", "27", "28", "29", "30"], {}, class: "form-control") %> 
									</div>	
								</div>								
							</div>
													
							<div class="form-group col-md-6">
									<strong>Preferred Gender (Optional)</strong>
									<%= f.select :gender_id, Gender.all.collect {|x| [x.name ,x.id]}, {:include_blank => "Select One"}, class: "form-control" %>
							</div>
						</div>			
						
						<h3>Contact Details</h3>
						<div class="row">
							<div class="form-group col-md-6">
								<strong>Contact Person *</strong>
								<%= f.text_field :contactperson, class: "form-control" %>
							</div>

							<div class="form-group col-md-6">
								<strong>Contact Number *</strong>
								<%= f.text_field :contactno, placeholder: "Ex. +919945508524", class: "form-control" %>
							</div>
						</div>
						
						<div class="form-group">
							<strong>Contact Email *</strong>
							<%= f.text_field :contactemail, placeholder: "Ex. ram@gmail.com", class: "form-control input" %>
						</div>

						
						<h3>Company Details</h3>
						<div class="row">
							<div class="form-group col-md-6">
								<strong>Company Name *</strong>
								<%= f.text_field :company, placeholder: "Ex. IBM, TechM, Wipro", class: "form-control" %>
							</div>

							<div class="form-group col-md-6">
								<strong>Company Url *</strong>
								<%= f.text_field :comurl, placeholder: "Ex. www.ibm.com", class: "form-control" %>
							</div>
						</div>

					
						<div class="hr-spacer"></div>
							<div class="col-fullwidth">							
								<strong>Description *</strong>
								<%= f.cktext_area :description, :ckeditor => {:toolbar => 'mini'} %><br>
						</div>
							
						<div class="form-group">
							
							<%= f.submit  value="Post Job", class: "btn btn-green" %>
						</div>
					</form>
					<div class="spacer-2">&nbsp;</div>
				</div>
				
				
				<div class="col-md-4">
					<div class="job-side-wrap">
						<li><%= link_to "HOME", root_path %></li>
					</div>
					
					<div class="job-side-wrap">
						<li><%= link_to "POST JOBS", new_job_path %></li>
					</div>

					<div class="job-side-wrap">
						<li><%= link_to "FIND JOBS", findjobs_path(:keyword => "Null", :location => "Null")   %></li>
					</div>

					<div class="job-side-wrap">
						<li><%= link_to "ABOUT US", about_path %></li>
					</div>
					<div class="job-side-wrap">
						<li><%= link_to "CONTACT US", new_contact_path %></li>
					</div>
					<div class="job-side-wrap">
						<li><%= link_to "CAREERS", career_path %></li>	
					</div>
				</div>
			</div>
		</div>

		<div id="page-content"><!-- start content -->
			<div class="content-about">
				<div id="cs"><!-- CS -->
					<div class="container">
					<div class="spacer-1">&nbsp;</div>
						<h2>Facing problem in posting jobs? </h2>
						<p>
							Please send job details on admin@ask4referral.com.
						</p>
						<h1 class="phone-cs">Call: +91-9945508524</h1>
					</div>
				</div><!-- CS -->
			</div><!-- end content -->
		</div><!-- end page content -->

<% end %>

app/views/jobs/show.html.erb
<div class="main-page-title"><!-- start main page title -->
			<div class="container">
				<div class="post-job-title">Job Description: </div>				
			</div>

</div><!-- end main page title -->

<p id="notice"><%= notice %></p>
<div class="container">
		<div class="spacer-1">&nbsp;</div>
			<div class="row">
				<div class="col-md-6">

					<strong>
					<%= link_to "Ask4Refferal", new_referral_path(:jobdesignation => @job.designation), class: "btn btn-green" %>
					</strong> 
					
					<br><br>
					<p>
					<em>Title:</em>
					<b><%= @job.title %></b>
					</p>
					
					<p>
					<em>Company:</em>
					<b><%= @job.company %></b>
					</p>
					
					<p>
					<em>Company url:</em>
					<b><%= @job.comurl %></b>
					</p>
					
					<p>
					<em>Designation:</em>
					<b><%= @job.designation %></b>
					</p>
					<!--
					<p>
					<em>Min Salary:</em>
					<b><%= @job.minsalary %></b>
					</p>
					
					<p>
					<em>Max Salary:</em>
					<b><%= @job.maxsalary %></b>
					</p>
					-->
					<p>
					<em>Min Experience:</em>
					<b><%= @job.minexp %></b><i> Years</i>
					</p>
					
					<p>
					<em>Max Experience:</em>
					<b><%= @job.maxexp %></b><i> Years</i>
					</p>
					
					<p>
					<em>Job Category:</em>
					<b><%= @job.category.name %></b>
					</p>
					
					<p>
					<em>Location:</em>
					<b><%= @job.location.name %></b>
					</p>
					
					<p>
					<em>Job Mode:</em>
					<b><%= @job.mode.name %></b>
					</p>
					
					<p>
					<em>Job Type:</em>
					<b><%= @job.jtype.name %></b>
					</p>
					
					<p>
					<em>Preferred Notice Period:</em>
					<b><%= @job.nperiod %></b><i> Days</i>
					</p>
				<!--	
					<p>
					<em>Gender:</em>
					<b><%= @job.gender.name %></b>
					</p>
				-->	
					<p>
					<em>Contact Person:</em>
					<b><%= @job.contactperson %></b>
					</p>
					
					<p>
					<em>Contact Email:</em>
					<b><%= @job.contactemail %></b>
					</p>
				<!--	
					<p>
					<em>Contact No:</em>
					<b><%= @job.contactno %></b>
					</p>
				-->
					<div class="hr-spacer100"></div></br>
					<p>
					<em>Description:</em>
					<%= sanitize(@job.description, :tags => ['strong', 'em', 'a', 'p', 'u', 'br', 'ul', 'li', 'b']) %>
					</p></br>
					<div class="hr-spacer100"></div>
					<!--
					<p>
					<em>Job Id:</em>
					<%= @job.id %>
					</p>
					-->
					
						
					<strong>
					<%= link_to "Ask4Refferal", new_referral_path(:jobdesignation => @job.designation), class: "btn btn-green" %>
					</strong> 
					
				</div>
				
				
				<div class="col-md-4">
					<div class="job-side-wrap">
						<li><%= link_to "HOME", root_path %></li>
					</div>
					
					<div class="job-side-wrap">
						<li><%= link_to "POST A JOB", new_job_path %></li>
					</div>

					<div class="job-side-wrap">
						<li><%= link_to "JOB SEARCH", findjobs_path(:keyword => "Null", :location => "Null")   %></li>
					</div>

					<div class="job-side-wrap">
						<li><%= link_to "ABOUT US", about_path %></li>
					</div>
					<div class="job-side-wrap">
						<li><%= link_to "CONTACT US", new_contact_path %></li>
					</div>
					<div class="job-side-wrap">
						<li><%= link_to "CAREERS", career_path %></li>	
					</div>
				</div>
			</div>
		</div>

		<br>
		
		<div id="page-content"><!-- start content -->
			<div class="content-about">
				<div id="cs"><!-- CS -->
					<div class="container">
					<div class="spacer-1">&nbsp;</div>
						<h2>Are you facing any issue? </h2>
						<p>
							We are happy to hear it. Please send details on info@ask4referral.com.
						</p>
						<h1 class="phone-cs">Call: +91-9945508524</h1>
					</div>
			</div><!-- CS -->
		</div><!-- end content -->
	</div><!-- end page content -->					

	