config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :referrals
  mount Ckeditor::Engine => '/ckeditor'
  get 'pages/about'

  
  
  get 'pages/career'
  get 'pages/robots'
  
  get 'jobs/findjobs'
  
  

  get 'about', :to => 'pages#about'
  
  get 'career', to: 'pages#career'
  get 'robots', to: 'pages#robots.txt'

  get 'findjobs', to: 'jobs#findjobs'
  
  
  
  resources :japprovals
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  resources :jobs
  resources :locations
  resources :genders
  resources :jtypes
  resources :modes
  resources :categories
  resources :pages
  resources :uploads
  resources :contacts
  get 'home/index'

 
  root 'jobs#index'
  
  
  
  ActiveAdmin.routes(self)
  get '*path', to: 'jobs#index'
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
		attr_accessible :company, :contactperson, :contactemail, :contactno, :description
		
		validates :contactperson, presence:true, length: {minimum:3, maximum:30}
		VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i	#         /^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/+\z/i
		validates :contactemail, presence:true, format: { with: VALID_EMAIL_REGEX }, length: {minimum:6, maximum:30}
		validates :contactno, numericality: true, length: {minimum:10, maximum:13}   # Need to create logic ,only number and + sign
		validates :description, presence:true, length: {minimum:10, maximum:3000}
	
end

app/models/gender.rb
class Gender < ActiveRecord::Base
end

app/models/japproval.rb
class Japproval < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
	attr_accessible :title, :company, :comurl, :designation, :minsalary, :maxsalary, :minexp, :maxexp, :category_id, :location_id, :mode_id, :jtype_id, :nperiod, :gender_id, :contactperson, :contactemail, :contactno, :description, :japproval_id
	belongs_to :category
	belongs_to :location
	belongs_to :mode
	belongs_to :jtype
	belongs_to :gender
	belongs_to :japproval
	
	
	validates :title, presence:true, length: {minimum:2, maximum:50}
	validates :company, presence:true, length: {minimum:3, maximum:50}
	validates :comurl, presence:true, length: {minimum:4, maximum:50}
	validates :minexp, presence:true, numericality: true, length: {minimum:1, maximum:2}
	validates :maxexp, presence:true, numericality: true, length: {minimum:1, maximum:2}
	validates :nperiod, presence:true, numericality: true, length: {minimum:1, maximum:2}
	validates :contactperson, presence:true, length: {minimum:3, maximum:50}
	
	validates :category, presence:true
	validates :location, presence:true
	validates :mode, presence:true
	validates :jtype, presence:true
	VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i	#         /^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/+\z/i
	validates :contactemail, presence:true, format: { with: VALID_EMAIL_REGEX }, length: {minimum:6, maximum:30}
	validates :contactno, presence:true, numericality: true, length: {minimum:10, maximum:13}   # Need to create logic ,only number and + sign
	validates :description, presence:true, length: {minimum:10, maximum:5000}
	
end

app/models/jtype.rb
class Jtype < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/mode.rb
class Mode < ActiveRecord::Base
end

app/models/referral.rb
class Referral < ActiveRecord::Base
    attr_accessible :fname, :lname, :company, :comurl, :designation, :currsalary, :expsalary, :exp, :location_id, :mode_id, :jtype_id, :nperiod, :gender_id, :contactemail, :contactno, :resume, :attachment, :jobid, :attachment_cache
    belongs_to :location
    belongs_to :mode
    belongs_to :jtype
    belongs_to :gender

	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
	
    validates :fname, presence:true, length: {minimum:2, maximum:15}
    validates :lname, presence:true, length: {minimum:2, maximum:15}
    validates :company, presence:true, length: {minimum:2, maximum:15}
    validates :comurl, presence:true, length: {minimum:4, maximum:30}
    validates :designation, presence:true, length: {minimum:2, maximum:30}
	validates :nperiod, presence:true, numericality: true, length: {minimum:1, maximum:2}
	
	validates :currsalary, presence:true, numericality: true, length: {minimum:1, maximum:2}
	validates :expsalary, presence:true, numericality: true, length: {minimum:1, maximum:2}
	validates :exp, presence:true, numericality: true, length: {minimum:1, maximum:2}
	validates :location, presence:true
	validates :mode, presence:true
	validates :jtype, presence:true
	
	VALID_EMAIL_REGEX =  /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i	#         /^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/+\z/i
	validates :contactemail, presence:true, format: { with: VALID_EMAIL_REGEX }, length: {minimum:6, maximum:40}
	validates :contactno, presence:true, numericality: true, length: {minimum:10, maximum:13}   # Need to create logic ,only number and + sign
	
	validates :attachment, presence:true
	
	validate :attachment_size_validation
	
	def attachment_size_validation
    errors[:attachment] << "should be less than 1MB" if attachment.size > 1.megabytes
    end
	
	    
end

app/models/upload.rb
class Upload < ActiveRecord::Base

 attr_accessible :attachment_cache
 
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/jtypes_helper.rb
module JtypesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/modes_helper.rb
module ModesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/referrals_helper.rb
module ReferralsHelper
end

app/views/layouts/application.html - Copy.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Ask4Referral, Get Referred, Get Hired, Fast Recruitment</title>
        <meta name="viewport" content="width=device-width">
        
        <!-- CSS -->
		<%= stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
  		<%= javascript_include_tag 'ckeditor\ckeditor.js' %>
        
               
        
        <style>      
            body {position: relative;}      
            table.main {zoom: 1;}
            table.main tr td {vertical-align: top;}
            table.main tr td:first-child, table.main tr td:last-child {width: 170px;}
            table.main tr td:first-child {padding-right: 10px; padding-top: 15px;}
            table.main tr td:last-child {padding-left: 10px; padding-top: 15px;}
            
            .coursesLinks {
                
            }
        </style>
    </head>
    <body>
        <table class="main" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <td>
                    
                </td>
                <td>
                    <div class="wrap clearfix">

<marquee ONMOUSEOVER="this.stop();"
            ONMOUSEOUT="this.start();"><font color="Blue">Welcome to Ask4Referral.com, Improvements are coming soon to the Ask4Referral.com, Suggestions/feedbacks on feedback@ask4refferal.com  </font></marquee>                        
		<header>
                <div class="topnav-wrap">
                    <div class="clearfix">
                        <nav role="navigation" class="main-nav">
                            <ul>
                                <li><%= link_to "Home", root_path %></li>
                                <li><%= link_to "Post Job", new_job_path %></li>
                                <li><%= link_to "Find Jobs", findjobs_path  %></li>
								<li><%= link_to "About Us", about_path %></li>
                                <li><%= link_to "Contact Us", contact_path %></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="padd-20 blackbox clearfix">
                    <div class="logo">
					<%= link_to root_path do %>
						<%= image_tag("logo.png", :alt => "Ask4Referral") %>
					<% end %>
					</div>
                </div>

		</header>                        
  

		<div class="hr-spacer"></div>				


<% flash.each do |key,value| %>
<p><%= value %></P>
<% end %>
		
<!--		<div class="hr-spacer100" ></div>
				</br>
				</br>				
				<strong class="home-col-left">Ads</strong>
				</br>
				</br>
		<div class="hr-spacer100"></div> -->
				
		<%= yield %>
											
											
<!--		<div class="hr-spacer100" ></div>
				</br>
				</br>				
				<strong class="home-col-left">Ads</strong> 
				</br>
				</br>
		<div class="hr-spacer100"></div>-->
		
		
		<footer>
                <div class="padd-15 blackbox clearfix">
                    <div class="foot-left">
                        <h4>About Ask4Referral</h4>
                        <p>Our mission is to speed up hiring process through removing the gap between the referrer and job seeker (referee), the point of contact for a Job Seeker will be the direct referrer working in the targeted company instead of the consultancy.</p>
			<h5> <li><%= link_to "read more", about_path %></li></h5>
                    </div>
                    <div class="foot-center">
                        <h4>Links</h4>
                        <ul class="foot-links">
						    <li><%= link_to "Home", root_path %></li>
                                <li><%= link_to "Post Job", new_job_path %></li>
                                <li><%= link_to "Find Jobs", findjobs_path %></li>
								<li><%= link_to "About Us", about_path %></li>
                                <li><%= link_to "Contact Us", contact_path %></li>
                        </ul>
                    </div>
                   <div class="foot-right">
                        <h4>Ask4Referral Pvt Ltd </h4>
                        <p>
                            Building Manyata, Near R.V. Public School<br>
                            Mavali, Bengaluru-560004, India<br>
                            Mobile: +91-9945508524</p>
                        <p>Email: <a href="mainto:contact_us@ask4referral.com" class="readmore">contact_us@ask4referral.com</a></p>
                    </div>
                </div>
		</footer>
                                </div>
                </td>
                <td>
				                 </td>
            </tr>
        </table>
			
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-89035465-1', 'auto');
  ga('send', 'pageview');

</script>
       
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        
        <title>Ask4Referral, Get Referred, Get Hired, Fast Recruitment</title>

        <meta name="viewport" content="width=device-width, initial-scale=0.15">
        
        <!-- CSS -->
		<%= stylesheet_link_tag  'style.css',  'bootstrap.min.css', 'font-awesome.css', 'jslider.css', 'jslider.round.css', 'owl.carousel.css', 'owl.theme.css', 'owl.transitions.css', media: 'all', 'data-turbolinks-track' => true %>
			
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
 	
	<%= favicon_link_tag 'favicon.ico' %>               
	<link rel="shortcut icon" type="image/x-icon" href="/assets/images/favicon.ico" />
	<link rel="shortcut icon" type="image/x-icon" href="favicon.ico?v2" />
      
    </head>
    
<!--
<marquee ONMOUSEOVER="this.stop();"
            ONMOUSEOUT="this.start();"><font color="Blue">Welcome to Ask4Referral.com, Improvements are coming soon to the Ask4Referral.com, Suggestions/feedbacks on feedback@ask4refferal.com  </font></marquee>                        
-->		
 <body>
	<div id="wrapper"><!-- start main wrapper -->
		<div id="header"><!-- start main header -->
			<div class="top-line">&nbsp;</div>
			<div class="top-line">&nbsp;</div>
			<div class="top"><!-- top -->
				<div class="container">
					<div class="media-top-right">
						
						
						<div class="clearfix"></div>
					</div>
				</div>
			</div><!-- top -->
			
			<div class="container"><!-- container -->
				<div class="row">
					<div class="col-md-4"><!-- logo -->
						<%= link_to root_path do %>
						<%= image_tag("logo_26.JPG", :alt => "Ask4Referral") %>
					<% end %>
					</div><!-- logo -->
					<div class="col-md-8 main-nav"><!-- Main Navigation -->
						
						<nav>
							<ul class="menu">
							
								<li><%= link_to "HOME", root_path %></li>
                                <li><%= link_to "POST JOBS", new_job_path %></li>
                                <li><%= link_to "FIND JOBS", findjobs_path(:keyword => "Null", :location => "Null")  %></li>
								<li><%= link_to "ABOUT US", about_path %></li>
                                <li><%= link_to "CONTACT US", new_contact_path %></li>
                                <li><%= link_to "CAREERS", career_path %></li>								
							</ul>
						</nav>
					</div><!-- Main Navigation -->
					<div class="clearfix"></div>
				</div>
			</div><!-- container -->
		</div><!-- end main header -->                       
  

					



		
<!--		<div class="hr-spacer100" ></div>
				</br>
				</br>				
				<strong class="home-col-left">Ads</strong>
				</br>
				</br>
		<div class="hr-spacer100"></div> -->
				
		<%= yield %>
											
											
<!--		<div class="hr-spacer100" ></div>
				</br>
				</br>				
				<strong class="home-col-left">Ads</strong> 
				</br>
				</br>
		<div class="hr-spacer100"></div>-->
		
		
	<div id="footer"><!-- Footer -->
			<div class="container"><!-- Container -->
				<div class="row">
					<div class="col-md-5 footer-widget"><!-- Text Widget -->
						<h6 class="widget-title">Our Mission</h6>
						<div class="textwidget">
							<p>Ask4Referral is to speed up the hiring process,we works on the professional networking principle.</p>
							<p>We guarantee instant job offer beacuse.....</p>
							<p>The survey data says that more than 60% jobs provided through internal referrals.</p>
							<p>We will take care of fastest processing of your resume and avoid them to be in black holes.</p>
							<p>Ask4Referral.com is free and will be free always...</p>
						</div>
					</div>
					
					<div class="col-md-3 footer-widget"><!-- Footer Menu Widget -->
						<h6 class="widget-title">Useful Links</h6>
						<div class="footer-widget-nav">
							<ul>
								<li><%= link_to "HOME", root_path %></li>
                                <li><%= link_to "POST JOBS", new_job_path %></li>
                                <li><%= link_to "FIND JOBS", findjobs_path(:keyword => "Null", :location => "Null")   %></li>
								<li><%= link_to "ABOUT US", about_path %></li>
                                <li><%= link_to "CONTACT US", new_contact_path %></li>
                                <li><%= link_to "CAREERS", career_path %></li>	
							</ul>
						</div>
					</div><!-- Footer Menu Widget -->
					
					
					<div class="col-md-4 footer-widget"><!-- News Leter Widget -->
						<h6 class="widget-title">Address</h6>
						<div class="textwidget">
							<p>Ask4Referral.com</p>
							<p>Building Manyata, Near R.V. Public School</p>
							<p>Mavali, Bengaluru-560004, India</p>
							<p>Mobile: +91-9945508524</p>
							<p>Email: <a href="contact_us@ask4referral.com"> contact_us@ask4referral.com</a></p>
						</div>

						
					<div class="clearfix"></div>
				</div>

				
				
			</div><!-- Container -->
			<div class="footer-credits">
					2016 <a href="Ask4Referral.com">Ask4Referral.com</a>. All Rights Reserved.
			</div>
			
		</div><!-- Footer -->
	</div><!-- end main wrapper -->
        


















		
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-89035465-1', 'auto');
  ga('send', 'pageview');

</script>
       
</body>
</html>